export {canonicalize} from './canonical.ts'
export {sha256Hex} from './hash.ts'
export {checkLock, lockHypothesis, missingFields, REQUIRED_HYPOTHESIS_FIELDS} from './preregistration.ts'
export type {LockCheck, PreregistrationLock} from './preregistration.ts'
export {loadRegistry} from './registry.ts'
export type {Deviation, Hypothesis, Registry, RegistryEntry} from './registry.ts'
