// Reference values: test/fixtures/stats.json, generated by scripts/stats_fixtures.py with
// SciPy, statsmodels and NumPy (versions recorded in the fixture).
import {describe, expect, test} from 'vitest'
import ref from './fixtures/stats.json' with {type: 'json'}
import {
  binomTest,
  circularBlockBootstrap,
  fisherExact,
  holm,
  lgamma,
  mannWhitneyU,
  mulberry32,
  normSf,
  quantile7,
  stratifiedBootstrap,
  verdict,
} from '../src/stats.ts'

// Relative tolerance, plus an optional absolute floor for values that are exactly zero.
const close = (actual: number, expected: number, rel = 1e-9, abs = 0) =>
  expect(Math.abs(actual - expected)).toBeLessThanOrEqual(rel * Math.abs(expected) + abs)

describe('special functions vs SciPy', () => {
  test('lgamma', () => ref.special.gammaln.forEach(({x, value}) => close(lgamma(x), value, 1e-12, 1e-14)))
  test('normal upper tail', () => ref.special.normSf.forEach(({z, value}) => close(normSf(z), value, 1e-12)))
})

describe('tests vs reference libraries', () => {
  test("Fisher's exact (R tolerance)", () => ref.fisher.forEach(({table, p}) => close(fisherExact(...(table as [number, number, number, number])), p)))
  test('exact binomial', () => ref.binomial.forEach(({k, n, p}) => close(binomTest(k, n), p)))
  test('Mann-Whitney U, tie + continuity corrected', () =>
    ref.mannWhitney.forEach(({x, y, U, p}) => {
      const r = mannWhitneyU(x, y)
      expect(r.U).toBe(U)
      close(r.p, p)
    }))
  test('Holm', () => ref.holm.forEach(({p, adjusted}) => holm(p).forEach((v, i) => close(v, adjusted[i]!, 1e-15))))
  test('quantile type 7', () =>
    ref.quantileType7.forEach(({values, probs, quantiles}) => {
      const sorted = [...values].sort((a, b) => a - b)
      probs.forEach((prob, i) => close(quantile7(sorted, prob), quantiles[i]!, 1e-12))
    }))
})

describe('seeded resampling', () => {
  test('mulberry32 is deterministic and in [0, 1)', () => {
    const a = mulberry32(20261004)
    const b = mulberry32(20261004)
    const xs = Array.from({length: 1000}, () => a())
    expect(xs).toEqual(Array.from({length: 1000}, () => b()))
    expect(Math.min(...xs)).toBeGreaterThanOrEqual(0)
    expect(Math.max(...xs)).toBeLessThan(1)
    expect(xs.reduce((s, v) => s + v, 0) / xs.length).toBeCloseTo(0.5, 1)
  })

  const series = Array.from({length: 3000}, (_, i) => Math.sin(i / 5) + (i % 7) / 10)
  const mean = (idx: Int32Array) => {
    let s = 0
    for (const i of idx) s += series[i]!
    return s / idx.length
  }

  test('circular block bootstrap is identical across runs with the seed', () => {
    const r1 = circularBlockBootstrap(series.length, 7, 2000, 20261004, mean)
    const r2 = circularBlockBootstrap(series.length, 7, 2000, 20261004, mean)
    expect(r1).toEqual(r2)
    expect(r1.effects).toHaveLength(2000)
    expect(r1.ciLow).toBeLessThan(mean(Int32Array.from(series.keys())))
    expect(r1.ciHigh).toBeGreaterThan(mean(Int32Array.from(series.keys())))
    expect(circularBlockBootstrap(series.length, 7, 2000, 1, mean).ciLow).not.toBe(r1.ciLow)
  })

  test('blocks are 7 consecutive indices that wrap around', () => {
    let seen: number[] = []
    circularBlockBootstrap(10, 7, 1, 20261004, (idx) => {
      seen = Array.from(idx)
      return 0
    })
    expect(seen).toHaveLength(10)
    for (let i = 1; i < 7; i++) expect(seen[i]).toBe((seen[0]! + i) % 10)
  })

  test('undefined resamples are dropped and counted', () => {
    let calls = 0
    const r = circularBlockBootstrap(50, 7, 100, 3, () => (calls++ % 10 === 0 ? null : 1))
    expect(r.undefinedResamples).toBe(10)
    expect(r.effects).toHaveLength(90)
  })

  test('stratified bootstrap keeps group sizes and is seeded', () => {
    const sizes: number[] = []
    const r = stratifiedBootstrap([12, 63], 500, 20261004, (groups) => {
      sizes.push(groups[0]!.length, groups[1]!.length)
      return groups[0]![0]! - groups[1]![0]!
    })
    expect(new Set(sizes)).toEqual(new Set([12, 63]))
    expect(r).toEqual(stratifiedBootstrap([12, 63], 500, 20261004, (g) => g[0]![0]! - g[1]![0]!))
  })
})

describe('locked verdict rules', () => {
  const pp = {nullValue: 0, sesoi: 5}
  test('Supported needs significance, the predicted direction and at least the SESOI', () => {
    expect(verdict({...pp, adjustedP: 0.01, effect: 6, ciHigh: 8})).toBe('Supported')
    expect(verdict({...pp, adjustedP: 0.01, effect: 5, ciHigh: 8})).toBe('Supported')
  })
  test('significant but smaller than the SESOI is Not supported', () => {
    expect(verdict({...pp, adjustedP: 1e-9, effect: 0.4, ciHigh: 0.9})).toBe('Not supported')
    expect(verdict({...pp, adjustedP: 0.01, effect: 4, ciHigh: 6})).toBe('Not supported')
  })
  test('significant in the opposite direction is Contradicted', () => {
    expect(verdict({...pp, adjustedP: 0.001, effect: -7, ciHigh: -4})).toBe('Contradicted')
  })
  test('not significant: Not supported if the CI excludes the SESOI, else Inconclusive', () => {
    expect(verdict({...pp, adjustedP: 0.3, effect: 1, ciHigh: 4.9})).toBe('Not supported')
    expect(verdict({...pp, adjustedP: 0.3, effect: 1, ciHigh: 5})).toBe('Inconclusive')
  })
  test('Groundhog: null 50%, SESOI 60% hit rate', () => {
    const g = {nullValue: 50, sesoi: 60}
    expect(verdict({...g, adjustedP: 0.2, effect: 40, ciHigh: 52})).toBe('Not supported')
    expect(verdict({...g, adjustedP: 0.04, effect: 36, ciHigh: 47})).toBe('Contradicted')
    expect(verdict({...g, adjustedP: 0.5, effect: 55, ciHigh: 66})).toBe('Inconclusive')
  })
})
